#!/bin/sh

for file in .gvimrc .vimrc
do
    if [[ (-e "$HOME/$file") && (! -L "$HOME/$file") ]]; then
        echo "Backing up $HOME/$file -> $HOME/$file.original"
        cp "$HOME/$file" "$HOME/$file.original"
    fi
done

echo 'Install plugins...'
vim -Ec "exec 'PlugInstall' | qa"
vim -Ec "exec 'CocInstall -sync '.join(g:coc_global_extensions, ' ') | qa"
